id: A453EF636
title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious Dorje
  Drolö'
type: translation
pechas:
- I8DF787C8
- IFBA39485
- I738D99E3
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:50:18.821871
  last_modified_at: 2023-01-04 12:50:18.821889
  collections:
  - Khenchen Jigme Phuntsok Series
  - Works of Tibetan Masters
alignment_to_base:
  I8DF787C8/2927: 4EA4
  IFBA39485/4D2F: 4EA4
  I738D99E3/8345: 4EA4
